/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityLevel = IDL.Variant({
  'info' : IDL.Null,
  'warn' : IDL.Null,
  'error' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'agentId' : IDL.Text,
  'level' : ActivityLevel,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'idle' : IDL.Null,
  'error' : IDL.Null,
  'offline' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'taskCount' : IDL.Nat,
  'modelName' : IDL.Text,
  'uptimePercentage' : IDL.Nat,
  'lastActive' : Time,
});
export const BrainEntry = IDL.Record({
  'id' : IDL.Text,
  'key' : IDL.Text,
  'value' : IDL.Text,
  'agentId' : IDL.Text,
  'category' : IDL.Text,
});
export const BroadcastMessage = IDL.Record({
  'id' : IDL.Text,
  'sentBy' : IDL.Text,
  'agentTargets' : IDL.Vec(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ConfigEntry = IDL.Record({
  'id' : IDL.Text,
  'key' : IDL.Text,
  'value' : IDL.Text,
  'agentId' : IDL.Text,
  'sensitive' : IDL.Bool,
});
export const Credit = IDL.Record({
  'id' : IDL.Text,
  'balance' : IDL.Nat,
  'agentId' : IDL.Text,
  'totalUsed' : IDL.Nat,
  'costAlerts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool)),
});
export const CronJob = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'idle' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
  }),
  'name' : IDL.Text,
  'agentId' : IDL.Text,
  'nextRun' : Time,
  'schedule' : IDL.Text,
  'lastRun' : Time,
});
export const LeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'agentName' : IDL.Text,
  'agentId' : IDL.Text,
  'uptimePercent' : IDL.Nat,
  'taskCount' : IDL.Nat,
  'creditsUsed' : IDL.Nat,
});
export const ProviderStatus = IDL.Variant({
  'down' : IDL.Null,
  'healthy' : IDL.Null,
  'degraded' : IDL.Null,
});
export const Provider = IDL.Record({
  'id' : IDL.Text,
  'status' : ProviderStatus,
  'model' : IDL.Text,
  'name' : IDL.Text,
  'latencyMs' : IDL.Nat,
  'uptimePercent' : IDL.Nat,
});
export const SecuritySeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const SecurityEvent = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'agentId' : IDL.Text,
  'timestamp' : Time,
  'severity' : SecuritySeverity,
  'eventType' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'agentId' : IDL.Text,
  'version' : IDL.Text,
  'enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addActivityLog' : IDL.Func([ActivityLog], [], []),
  'addAgent' : IDL.Func([Agent], [], []),
  'addBrainEntry' : IDL.Func([BrainEntry], [], []),
  'addBroadcastMessage' : IDL.Func([BroadcastMessage], [], []),
  'addConfigEntry' : IDL.Func([ConfigEntry], [], []),
  'addCredit' : IDL.Func([Credit], [], []),
  'addCronJob' : IDL.Func([CronJob], [], []),
  'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'addProvider' : IDL.Func([Provider], [], []),
  'addSecurityEvent' : IDL.Func([SecurityEvent], [], []),
  'addSkill' : IDL.Func([Skill], [], []),
  'getAgent' : IDL.Func([IDL.Text], [Agent], ['query']),
  'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getAllBrainEntries' : IDL.Func([], [IDL.Vec(BrainEntry)], ['query']),
  'getAllBroadcastMessages' : IDL.Func(
      [],
      [IDL.Vec(BroadcastMessage)],
      ['query'],
    ),
  'getAllConfigEntries' : IDL.Func([], [IDL.Vec(ConfigEntry)], ['query']),
  'getAllCredits' : IDL.Func([], [IDL.Vec(Credit)], ['query']),
  'getAllCronJobs' : IDL.Func([], [IDL.Vec(CronJob)], ['query']),
  'getAllLeaderboardEntries' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
  'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityLevel = IDL.Variant({
    'info' : IDL.Null,
    'warn' : IDL.Null,
    'error' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivityLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'agentId' : IDL.Text,
    'level' : ActivityLevel,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'idle' : IDL.Null,
    'error' : IDL.Null,
    'offline' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'taskCount' : IDL.Nat,
    'modelName' : IDL.Text,
    'uptimePercentage' : IDL.Nat,
    'lastActive' : Time,
  });
  const BrainEntry = IDL.Record({
    'id' : IDL.Text,
    'key' : IDL.Text,
    'value' : IDL.Text,
    'agentId' : IDL.Text,
    'category' : IDL.Text,
  });
  const BroadcastMessage = IDL.Record({
    'id' : IDL.Text,
    'sentBy' : IDL.Text,
    'agentTargets' : IDL.Vec(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ConfigEntry = IDL.Record({
    'id' : IDL.Text,
    'key' : IDL.Text,
    'value' : IDL.Text,
    'agentId' : IDL.Text,
    'sensitive' : IDL.Bool,
  });
  const Credit = IDL.Record({
    'id' : IDL.Text,
    'balance' : IDL.Nat,
    'agentId' : IDL.Text,
    'totalUsed' : IDL.Nat,
    'costAlerts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool)),
  });
  const CronJob = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'idle' : IDL.Null,
      'failed' : IDL.Null,
      'running' : IDL.Null,
    }),
    'name' : IDL.Text,
    'agentId' : IDL.Text,
    'nextRun' : Time,
    'schedule' : IDL.Text,
    'lastRun' : Time,
  });
  const LeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'agentName' : IDL.Text,
    'agentId' : IDL.Text,
    'uptimePercent' : IDL.Nat,
    'taskCount' : IDL.Nat,
    'creditsUsed' : IDL.Nat,
  });
  const ProviderStatus = IDL.Variant({
    'down' : IDL.Null,
    'healthy' : IDL.Null,
    'degraded' : IDL.Null,
  });
  const Provider = IDL.Record({
    'id' : IDL.Text,
    'status' : ProviderStatus,
    'model' : IDL.Text,
    'name' : IDL.Text,
    'latencyMs' : IDL.Nat,
    'uptimePercent' : IDL.Nat,
  });
  const SecuritySeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SecurityEvent = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'agentId' : IDL.Text,
    'timestamp' : Time,
    'severity' : SecuritySeverity,
    'eventType' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'agentId' : IDL.Text,
    'version' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'addActivityLog' : IDL.Func([ActivityLog], [], []),
    'addAgent' : IDL.Func([Agent], [], []),
    'addBrainEntry' : IDL.Func([BrainEntry], [], []),
    'addBroadcastMessage' : IDL.Func([BroadcastMessage], [], []),
    'addConfigEntry' : IDL.Func([ConfigEntry], [], []),
    'addCredit' : IDL.Func([Credit], [], []),
    'addCronJob' : IDL.Func([CronJob], [], []),
    'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'addProvider' : IDL.Func([Provider], [], []),
    'addSecurityEvent' : IDL.Func([SecurityEvent], [], []),
    'addSkill' : IDL.Func([Skill], [], []),
    'getAgent' : IDL.Func([IDL.Text], [Agent], ['query']),
    'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getAllBrainEntries' : IDL.Func([], [IDL.Vec(BrainEntry)], ['query']),
    'getAllBroadcastMessages' : IDL.Func(
        [],
        [IDL.Vec(BroadcastMessage)],
        ['query'],
      ),
    'getAllConfigEntries' : IDL.Func([], [IDL.Vec(ConfigEntry)], ['query']),
    'getAllCredits' : IDL.Func([], [IDL.Vec(Credit)], ['query']),
    'getAllCronJobs' : IDL.Func([], [IDL.Vec(CronJob)], ['query']),
    'getAllLeaderboardEntries' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
    'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };