/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'info' : null } |
  { 'warn' : null } |
  { 'error' : null };
export interface ActivityLog {
  'id' : string,
  'action' : string,
  'agentId' : string,
  'level' : ActivityLevel,
  'timestamp' : Time,
  'details' : string,
}
export interface Agent {
  'id' : string,
  'status' : Status,
  'name' : string,
  'description' : string,
  'taskCount' : bigint,
  'modelName' : string,
  'uptimePercentage' : bigint,
  'lastActive' : Time,
}
export interface BrainEntry {
  'id' : string,
  'key' : string,
  'value' : string,
  'agentId' : string,
  'category' : string,
}
export interface BroadcastMessage {
  'id' : string,
  'sentBy' : string,
  'agentTargets' : Array<string>,
  'message' : string,
  'timestamp' : Time,
}
export interface ConfigEntry {
  'id' : string,
  'key' : string,
  'value' : string,
  'agentId' : string,
  'sensitive' : boolean,
}
export interface Credit {
  'id' : string,
  'balance' : bigint,
  'agentId' : string,
  'totalUsed' : bigint,
  'costAlerts' : Array<[bigint, boolean]>,
}
export interface CronJob {
  'id' : string,
  'status' : { 'idle' : null } |
    { 'failed' : null } |
    { 'running' : null },
  'name' : string,
  'agentId' : string,
  'nextRun' : Time,
  'schedule' : string,
  'lastRun' : Time,
}
export interface LeaderboardEntry {
  'rank' : bigint,
  'agentName' : string,
  'agentId' : string,
  'uptimePercent' : bigint,
  'taskCount' : bigint,
  'creditsUsed' : bigint,
}
export interface Provider {
  'id' : string,
  'status' : ProviderStatus,
  'model' : string,
  'name' : string,
  'latencyMs' : bigint,
  'uptimePercent' : bigint,
}
export type ProviderStatus = { 'down' : null } |
  { 'healthy' : null } |
  { 'degraded' : null };
export interface SecurityEvent {
  'id' : string,
  'description' : string,
  'agentId' : string,
  'timestamp' : Time,
  'severity' : SecuritySeverity,
  'eventType' : string,
}
export type SecuritySeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Skill {
  'id' : string,
  'name' : string,
  'description' : string,
  'agentId' : string,
  'version' : string,
  'enabled' : boolean,
}
export type Status = { 'active' : null } |
  { 'idle' : null } |
  { 'error' : null } |
  { 'offline' : null };
export type Time = bigint;
export interface _SERVICE {
  'addActivityLog' : ActorMethod<[ActivityLog], undefined>,
  'addAgent' : ActorMethod<[Agent], undefined>,
  'addBrainEntry' : ActorMethod<[BrainEntry], undefined>,
  'addBroadcastMessage' : ActorMethod<[BroadcastMessage], undefined>,
  'addConfigEntry' : ActorMethod<[ConfigEntry], undefined>,
  'addCredit' : ActorMethod<[Credit], undefined>,
  'addCronJob' : ActorMethod<[CronJob], undefined>,
  'addLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'addProvider' : ActorMethod<[Provider], undefined>,
  'addSecurityEvent' : ActorMethod<[SecurityEvent], undefined>,
  'addSkill' : ActorMethod<[Skill], undefined>,
  'getAgent' : ActorMethod<[string], Agent>,
  'getAllActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getAllBrainEntries' : ActorMethod<[], Array<BrainEntry>>,
  'getAllBroadcastMessages' : ActorMethod<[], Array<BroadcastMessage>>,
  'getAllConfigEntries' : ActorMethod<[], Array<ConfigEntry>>,
  'getAllCredits' : ActorMethod<[], Array<Credit>>,
  'getAllCronJobs' : ActorMethod<[], Array<CronJob>>,
  'getAllLeaderboardEntries' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getAllProviders' : ActorMethod<[], Array<Provider>>,
  'getAllSecurityEvents' : ActorMethod<[], Array<SecurityEvent>>,
  'getAllSkills' : ActorMethod<[], Array<Skill>>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];