/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BroadcastMessage {
    id: string;
    sentBy: string;
    agentTargets: Array<string>;
    message: string;
    timestamp: Time;
}
export interface LeaderboardEntry {
    rank: bigint;
    agentName: string;
    agentId: string;
    uptimePercent: bigint;
    taskCount: bigint;
    creditsUsed: bigint;
}
export type Time = bigint;
export interface ConfigEntry {
    id: string;
    key: string;
    value: string;
    agentId: string;
    sensitive: boolean;
}
export interface SecurityEvent {
    id: string;
    description: string;
    agentId: string;
    timestamp: Time;
    severity: SecuritySeverity;
    eventType: string;
}
export interface ActivityLog {
    id: string;
    action: string;
    agentId: string;
    level: ActivityLevel;
    timestamp: Time;
    details: string;
}
export interface Credit {
    id: string;
    balance: bigint;
    agentId: string;
    totalUsed: bigint;
    costAlerts: Array<[bigint, boolean]>;
}
export interface Agent {
    id: string;
    status: Status;
    name: string;
    description: string;
    taskCount: bigint;
    modelName: string;
    uptimePercentage: bigint;
    lastActive: Time;
}
export interface Skill {
    id: string;
    name: string;
    description: string;
    agentId: string;
    version: string;
    enabled: boolean;
}
export interface Provider {
    id: string;
    status: ProviderStatus;
    model: string;
    name: string;
    latencyMs: bigint;
    uptimePercent: bigint;
}
export interface BrainEntry {
    id: string;
    key: string;
    value: string;
    agentId: string;
    category: string;
}
export interface CronJob {
    id: string;
    status: Variant_idle_failed_running;
    name: string;
    agentId: string;
    nextRun: Time;
    schedule: string;
    lastRun: Time;
}
export enum ActivityLevel {
    info = "info",
    warn = "warn",
    error = "error"
}
export enum ProviderStatus {
    down = "down",
    healthy = "healthy",
    degraded = "degraded"
}
export enum SecuritySeverity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    active = "active",
    idle = "idle",
    error = "error",
    offline = "offline"
}
export enum Variant_idle_failed_running {
    idle = "idle",
    failed = "failed",
    running = "running"
}
export interface backendInterface {
    addActivityLog(log: ActivityLog): Promise<void>;
    addAgent(agent: Agent): Promise<void>;
    addBrainEntry(entry: BrainEntry): Promise<void>;
    addBroadcastMessage(message: BroadcastMessage): Promise<void>;
    addConfigEntry(entry: ConfigEntry): Promise<void>;
    addCredit(credit: Credit): Promise<void>;
    addCronJob(cronJob: CronJob): Promise<void>;
    addLeaderboardEntry(entry: LeaderboardEntry): Promise<void>;
    addProvider(provider: Provider): Promise<void>;
    addSecurityEvent(event: SecurityEvent): Promise<void>;
    addSkill(skill: Skill): Promise<void>;
    getAgent(id: string): Promise<Agent>;
    getAllActivityLogs(): Promise<Array<ActivityLog>>;
    getAllAgents(): Promise<Array<Agent>>;
    getAllBrainEntries(): Promise<Array<BrainEntry>>;
    getAllBroadcastMessages(): Promise<Array<BroadcastMessage>>;
    getAllConfigEntries(): Promise<Array<ConfigEntry>>;
    getAllCredits(): Promise<Array<Credit>>;
    getAllCronJobs(): Promise<Array<CronJob>>;
    getAllLeaderboardEntries(): Promise<Array<LeaderboardEntry>>;
    getAllProviders(): Promise<Array<Provider>>;
    getAllSecurityEvents(): Promise<Array<SecurityEvent>>;
    getAllSkills(): Promise<Array<Skill>>;
    seedData(): Promise<void>;
}
import type { ActivityLevel as _ActivityLevel, ActivityLog as _ActivityLog, Agent as _Agent, CronJob as _CronJob, Provider as _Provider, ProviderStatus as _ProviderStatus, SecurityEvent as _SecurityEvent, SecuritySeverity as _SecuritySeverity, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivityLog(arg0: ActivityLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivityLog(to_candid_ActivityLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivityLog(to_candid_ActivityLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addAgent(arg0: Agent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBrainEntry(arg0: BrainEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBrainEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBrainEntry(arg0);
            return result;
        }
    }
    async addBroadcastMessage(arg0: BroadcastMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBroadcastMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBroadcastMessage(arg0);
            return result;
        }
    }
    async addConfigEntry(arg0: ConfigEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addConfigEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addConfigEntry(arg0);
            return result;
        }
    }
    async addCredit(arg0: Credit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredit(arg0);
            return result;
        }
    }
    async addCronJob(arg0: CronJob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCronJob(to_candid_CronJob_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCronJob(to_candid_CronJob_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLeaderboardEntry(arg0: LeaderboardEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeaderboardEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeaderboardEntry(arg0);
            return result;
        }
    }
    async addProvider(arg0: Provider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProvider(to_candid_Provider_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProvider(to_candid_Provider_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSecurityEvent(arg0: SecurityEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecurityEvent(to_candid_SecurityEvent_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecurityEvent(to_candid_SecurityEvent_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSkill(arg0: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0);
            return result;
        }
    }
    async getAgent(arg0: string): Promise<Agent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_Agent_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_Agent_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivityLogs();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivityLogs();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBrainEntries(): Promise<Array<BrainEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBrainEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBrainEntries();
            return result;
        }
    }
    async getAllBroadcastMessages(): Promise<Array<BroadcastMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBroadcastMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBroadcastMessages();
            return result;
        }
    }
    async getAllConfigEntries(): Promise<Array<ConfigEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConfigEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConfigEntries();
            return result;
        }
    }
    async getAllCredits(): Promise<Array<Credit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCredits();
            return result;
        }
    }
    async getAllCronJobs(): Promise<Array<CronJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCronJobs();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCronJobs();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeaderboardEntries(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaderboardEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaderboardEntries();
            return result;
        }
    }
    async getAllProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSecurityEvents(): Promise<Array<SecurityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSecurityEvents();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSecurityEvents();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSkills();
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
}
function from_candid_ActivityLevel_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityLog_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLog): ActivityLog {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Agent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CronJob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CronJob): CronJob {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderStatus): ProviderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Provider_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Provider): Provider {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SecurityEvent_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityEvent): SecurityEvent {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SecuritySeverity_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecuritySeverity): SecuritySeverity {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    name: string;
    description: string;
    taskCount: bigint;
    modelName: string;
    uptimePercentage: bigint;
    lastActive: _Time;
}): {
    id: string;
    status: Status;
    name: string;
    description: string;
    taskCount: bigint;
    modelName: string;
    uptimePercentage: bigint;
    lastActive: Time;
} {
    return {
        id: value.id,
        status: from_candid_Status_n22(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        taskCount: value.taskCount,
        modelName: value.modelName,
        uptimePercentage: value.uptimePercentage,
        lastActive: value.lastActive
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    agentId: string;
    level: _ActivityLevel;
    timestamp: _Time;
    details: string;
}): {
    id: string;
    action: string;
    agentId: string;
    level: ActivityLevel;
    timestamp: Time;
    details: string;
} {
    return {
        id: value.id,
        action: value.action,
        agentId: value.agentId,
        level: from_candid_ActivityLevel_n27(_uploadFile, _downloadFile, value.level),
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        idle: null;
    } | {
        failed: null;
    } | {
        running: null;
    };
    name: string;
    agentId: string;
    nextRun: _Time;
    schedule: string;
    lastRun: _Time;
}): {
    id: string;
    status: Variant_idle_failed_running;
    name: string;
    agentId: string;
    nextRun: Time;
    schedule: string;
    lastRun: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        name: value.name,
        agentId: value.agentId,
        nextRun: value.nextRun,
        schedule: value.schedule,
        lastRun: value.lastRun
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ProviderStatus;
    model: string;
    name: string;
    latencyMs: bigint;
    uptimePercent: bigint;
}): {
    id: string;
    status: ProviderStatus;
    model: string;
    name: string;
    latencyMs: bigint;
    uptimePercent: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProviderStatus_n37(_uploadFile, _downloadFile, value.status),
        model: value.model,
        name: value.name,
        latencyMs: value.latencyMs,
        uptimePercent: value.uptimePercent
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    agentId: string;
    timestamp: _Time;
    severity: _SecuritySeverity;
    eventType: string;
}): {
    id: string;
    description: string;
    agentId: string;
    timestamp: Time;
    severity: SecuritySeverity;
    eventType: string;
} {
    return {
        id: value.id,
        description: value.description,
        agentId: value.agentId,
        timestamp: value.timestamp,
        severity: from_candid_SecuritySeverity_n42(_uploadFile, _downloadFile, value.severity),
        eventType: value.eventType
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    idle: null;
} | {
    error: null;
} | {
    offline: null;
}): Status {
    return "active" in value ? Status.active : "idle" in value ? Status.idle : "error" in value ? Status.error : "offline" in value ? Status.offline : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    info: null;
} | {
    warn: null;
} | {
    error: null;
}): ActivityLevel {
    return "info" in value ? ActivityLevel.info : "warn" in value ? ActivityLevel.warn : "error" in value ? ActivityLevel.error : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    failed: null;
} | {
    running: null;
}): Variant_idle_failed_running {
    return "idle" in value ? Variant_idle_failed_running.idle : "failed" in value ? Variant_idle_failed_running.failed : "running" in value ? Variant_idle_failed_running.running : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    down: null;
} | {
    healthy: null;
} | {
    degraded: null;
}): ProviderStatus {
    return "down" in value ? ProviderStatus.down : "healthy" in value ? ProviderStatus.healthy : "degraded" in value ? ProviderStatus.degraded : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): SecuritySeverity {
    return "low" in value ? SecuritySeverity.low : "high" in value ? SecuritySeverity.high : "medium" in value ? SecuritySeverity.medium : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLog>): Array<ActivityLog> {
    return value.map((x)=>from_candid_ActivityLog_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CronJob>): Array<CronJob> {
    return value.map((x)=>from_candid_CronJob_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Provider>): Array<Provider> {
    return value.map((x)=>from_candid_Provider_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SecurityEvent>): Array<SecurityEvent> {
    return value.map((x)=>from_candid_SecurityEvent_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLog): _ActivityLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Agent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Agent): _Agent {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CronJob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CronJob): _CronJob {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ProviderStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderStatus): _ProviderStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Provider_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Provider): _Provider {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SecurityEvent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecurityEvent): _SecurityEvent {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SecuritySeverity_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecuritySeverity): _SecuritySeverity {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_idle_failed_running;
    name: string;
    agentId: string;
    nextRun: Time;
    schedule: string;
    lastRun: Time;
}): {
    id: string;
    status: {
        idle: null;
    } | {
        failed: null;
    } | {
        running: null;
    };
    name: string;
    agentId: string;
    nextRun: _Time;
    schedule: string;
    lastRun: _Time;
} {
    return {
        id: value.id,
        status: to_candid_variant_n11(_uploadFile, _downloadFile, value.status),
        name: value.name,
        agentId: value.agentId,
        nextRun: value.nextRun,
        schedule: value.schedule,
        lastRun: value.lastRun
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ProviderStatus;
    model: string;
    name: string;
    latencyMs: bigint;
    uptimePercent: bigint;
}): {
    id: string;
    status: _ProviderStatus;
    model: string;
    name: string;
    latencyMs: bigint;
    uptimePercent: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ProviderStatus_n14(_uploadFile, _downloadFile, value.status),
        model: value.model,
        name: value.name,
        latencyMs: value.latencyMs,
        uptimePercent: value.uptimePercent
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    agentId: string;
    timestamp: Time;
    severity: SecuritySeverity;
    eventType: string;
}): {
    id: string;
    description: string;
    agentId: string;
    timestamp: _Time;
    severity: _SecuritySeverity;
    eventType: string;
} {
    return {
        id: value.id,
        description: value.description,
        agentId: value.agentId,
        timestamp: value.timestamp,
        severity: to_candid_SecuritySeverity_n18(_uploadFile, _downloadFile, value.severity),
        eventType: value.eventType
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    agentId: string;
    level: ActivityLevel;
    timestamp: Time;
    details: string;
}): {
    id: string;
    action: string;
    agentId: string;
    level: _ActivityLevel;
    timestamp: _Time;
    details: string;
} {
    return {
        id: value.id,
        action: value.action,
        agentId: value.agentId,
        level: to_candid_ActivityLevel_n3(_uploadFile, _downloadFile, value.level),
        timestamp: value.timestamp,
        details: value.details
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    name: string;
    description: string;
    taskCount: bigint;
    modelName: string;
    uptimePercentage: bigint;
    lastActive: Time;
}): {
    id: string;
    status: _Status;
    name: string;
    description: string;
    taskCount: bigint;
    modelName: string;
    uptimePercentage: bigint;
    lastActive: _Time;
} {
    return {
        id: value.id,
        status: to_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        taskCount: value.taskCount,
        modelName: value.modelName,
        uptimePercentage: value.uptimePercentage,
        lastActive: value.lastActive
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_idle_failed_running): {
    idle: null;
} | {
    failed: null;
} | {
    running: null;
} {
    return value == Variant_idle_failed_running.idle ? {
        idle: null
    } : value == Variant_idle_failed_running.failed ? {
        failed: null
    } : value == Variant_idle_failed_running.running ? {
        running: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderStatus): {
    down: null;
} | {
    healthy: null;
} | {
    degraded: null;
} {
    return value == ProviderStatus.down ? {
        down: null
    } : value == ProviderStatus.healthy ? {
        healthy: null
    } : value == ProviderStatus.degraded ? {
        degraded: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecuritySeverity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == SecuritySeverity.low ? {
        low: null
    } : value == SecuritySeverity.high ? {
        high: null
    } : value == SecuritySeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    info: null;
} | {
    warn: null;
} | {
    error: null;
} {
    return value == ActivityLevel.info ? {
        info: null
    } : value == ActivityLevel.warn ? {
        warn: null
    } : value == ActivityLevel.error ? {
        error: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    idle: null;
} | {
    error: null;
} | {
    offline: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.idle ? {
        idle: null
    } : value == Status.error ? {
        error: null
    } : value == Status.offline ? {
        offline: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
